#!/bin/sh
#
# @name UAHRQD
#
# @output Motor1 rover motor left
# @output Motor2 rover motor right
# @output Motor3 copter motor 11
# @output Motor4 copter motor 12
# @output Motor5 copter motor 21
# @output Motor6 copter motor 22

# @type hybrid
# @class hybrid
#
# @maintainer Automatic Class of Y23 Indian Institute of Technology Kanpur <mridulsen23@iitk.ac.in>
#

. ${R}etc/init.d/rc.hybrid_defaults

param set-default BAT1_N_CELLS 4

param set-default EKF2_ANGERR_INIT 0.01
param set-default EKF2_GBIAS_INIT 0.01
param set-default EKF2_MAG_TYPE 1

param set-default FW_AIRSPD_MAX 3
param set-default FW_AIRSPD_MIN 0
param set-default FW_AIRSPD_TRIM 1

# Settings for a typical wheelbase 0f 0.3m
param set-default GND_L1_DIST 1
param set-default GND_L1_PERIOD 5
param set-default GND_SP_CTRL_MODE 1
param set-default GND_SPEED_P 0.25
param set-default GND_SPEED_I 3
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_IMAX 0.125
param set-default GND_SPEED_THR_SC 1
param set-default GND_THR_CRUISE 0.3
param set-default GND_THR_MAX 0.5
param set-default GND_THR_MIN 0

#need to change if doesnt work
param set-default NAV_ACC_RAD 0.5

param set-default CA_AIRFRAME 5
#For turning
param set-default GND_MAX_ANG 3.142
param set-default GND_WHEEL_BASE 0.3

#need to change if doesnt work
param set-default CA_R_REV 1
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC6 101
param set-default PWM_MAIN_FUNC7 101

param set-default CA_ROTOR_COUNT 6
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR1_PX 0.15
param set-default CA_ROTOR1_PY 0.15
param set-default CA_ROTOR2_PX -0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY -0.15
param set-default CA_ROTOR4_PX 0.15
param set-default CA_ROTOR4_PY -0.15
param set-default CA_ROTOR4_KM -0.05
param set-default CA_ROTOR5_PX -0.15
param set-default CA_ROTOR5_PY 0.15
param set-default CA_ROTOR5_KM -0.05
